# Generated by Django 4.0.4 on 2022-05-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentue', models.TextField()),
                ('auteur', models.CharField(max_length=64, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
