# Generated by Django 4.0.4 on 2022-05-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='auteur',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tips',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
