# Generated by Django 4.0.4 on 2022-05-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_alter_tips_auteur_alter_tips_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_trip', models.IntegerField(default=0)),
                ('auteur', models.CharField(max_length=64)),
                ('voice', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tips',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tips',
            name='up',
            field=models.IntegerField(default=0),
        ),
    ]
